[package]
name = "minnie"
version = "0.1.0"
authors = ["Lymia Aluysia <lymia@lymiahugs.com>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
crossbeam-channel = "0.3"
derivative = "1.0.2"
enumset = { version = "0.4.0", features = ["serde", "nightly"] }
failure = "0.1.5"
futures01 = { package = "futures", version = "0.1.21", features = ["nightly"] }
futures-preview = { version = "0.3.0-alpha.18", features = ["compat", "io-compat", "nightly", "async-await"] }
flate2 = { version = "1.0.7", default-features = false, features = ["rust_backend"] }
lazy_static = "1.4.0"
log = "0.4.6"
parking_lot = "0.9.0"
reqwest = { version = "0.9.15", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0.90", features = ["rc"] }
serde_derive = "1.0.90"
serde_json = "1.0.39"
serde_repr = "0.1.4"
serde_with = "1.3.1"
strum = "0.16.0"
strum_macros = "0.16.0"
tokio = "0.1.18"
tokio-rustls = "0.9.2"
twox-hash = "1.5"
url = "1.7.2"
webpki = "0.19"
webpki-roots = "0.16"
websocket = { version = "0.23.0", default-features = false, features = ["async", "nightly"] }

[dev-dependencies]
simple_logger = "1.0.1"
