[package]
name = "minnie"
version = "0.1.0"
authors = ["Lymia Aluysia <lymia@lymiahugs.com>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = true

[dependencies]
derivative = "1.0.2"
enumset = { version = "0.3.18", features = ["serde"] }
failure = "0.1.5"
futures01 = { package = "futures", version = "0.1.21", features = ["nightly"] }
futures-preview = { version = "0.3.0-alpha.15", features = ["compat", "io-compat", "nightly", "async-await"] }
flate2 = { version = "1.0.7", default-features = false }
log = "0.4.6"
parking_lot = "0.7.1"
reqwest = { version = "0.9.15", default-features = false, features = ["rustls-tls"] }
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
serde_repr = "0.1.4"
static-events = { version = "0.2.0", git = "https://github.com/Lymia/static-events.git", rev = "224788b" }
tokio = "0.1.18"
tokio-rustls = "0.9.2"
url = "1.7.2"
websocket = { version = "0.22.3", default-features = false, features = ["async", "nightly"] }

[dev-dependencies]
simple_logger = "1.0.1"